#!/bin/sh

if [ "${SLB_REPORT_PRIVATE}" = "1" ]
then
	printf "ip4:\n" > $1
	/usr/sbin/ip --family inet addr > $1
	
	printf "ip6:\n" > $1
	/usr/sbin/ip --family inet6 addr > $1
else
	/usr/sbin/ip addr > $1
fi


